// <auto-generated />
using System;
using E_learninig.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


namespace E_learninig.Migrations
{
    [DbContext(typeof(EleariningContext))]
    [Migration("20260114205735_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
 //612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_learninig.Models.Course", b =>
            {
                b.Property<int>("CourseId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                b.Property<int>("Credits")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CourseId");

                b.ToTable("Course");

                b.HasData(
                    new
                    {
                        CourseId = 1,
                        Credits = 3,
                        Title = "Math "
                    },
                    new
                    {
                        CourseId = 2,
                        Credits = 4,
                        Title = "Physics "
                    },
                    new
                    {
                        CourseId = 3,
                        Credits = 3,
                        Title = "Programming C#"
                    },
                    new
                    {
                        CourseId = 4,
                        Credits = 2,
                        Title = "English"
                    });
            });

            modelBuilder.Entity("E_learninig.Models.Enrollment", b =>
            {
                b.Property<int>("EnrollmentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"), 1L, 1);

                b.Property<int>("CourseId")
                    .HasColumnType("int");

                b.Property<DateTime>("EnrollmentDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Grade")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StudentId")
                    .HasColumnType("int");

                b.HasKey("EnrollmentId");

                b.HasIndex("CourseId");

                b.HasIndex("StudentId");

                b.ToTable("Enrollment");

                b.HasData(
                    new
                    {
                        EnrollmentId = 1,
                        CourseId = 1,
                        EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "A",
                        StudentId = 1
                    },
                    new
                    {
                        EnrollmentId = 2,
                        CourseId = 3,
                        EnrollmentDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "B+",
                        StudentId = 1
                    },
                    new
                    {
                        EnrollmentId = 3,
                        CourseId = 2,
                        EnrollmentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "A-",
                        StudentId = 2
                    },
                    new
                    {
                        EnrollmentId = 4,
                        CourseId = 4,
                        EnrollmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "B",
                        StudentId = 2
                    },
                    new
                    {
                        EnrollmentId = 5,
                        CourseId = 1,
                        EnrollmentDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "C+",
                        StudentId = 3
                    },
                    new
                    {
                        EnrollmentId = 6,
                        CourseId = 3,
                        EnrollmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Grade = "B",
                        StudentId = 4
                    });
            });

            modelBuilder.Entity("E_learninig.Models.Student", b =>
            {
                b.Property<int>("StudentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StudentId");

                b.ToTable("Student");

                b.HasData(
                    new
                    {
                        StudentId = 1,
                        Email = "ahmad@student.com",
                        FirstName = "Ahmad",
                        LastName = "Ali",
                        Password = "123456"
                    },
                    new
                    {
                        StudentId = 2,
                        Email = "sara@student.com",
                        FirstName = "Sara",
                        LastName = "Mohammad",
                        Password = "123456"
                    },
                    new
                    {
                        StudentId = 3,
                        Email = "omar@student.com",
                        FirstName = "Omar",
                        LastName = "Hassan",
                        Password = "123456"
                    },
                    new
                    {
                        StudentId = 4,
                        Email = "laila@student.com",
                        FirstName = "Laila",
                        LastName = "Mahmoud",
                        Password = "123456"
                    });
            });

            modelBuilder.Entity("E_learninig.Models.Enrollment", b =>
            {
                b.HasOne("E_learninig.Models.Course", "Course")
                    .WithMany("Enrollments")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("E_learninig.Models.Student", "Student")
                    .WithMany("Enrollments")
                    .HasForeignKey("StudentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");

                b.Navigation("Student");
            });

            modelBuilder.Entity("E_learninig.Models.Course", b =>
            {
                b.Navigation("Enrollments");
            });

            modelBuilder.Entity("E_learninig.Models.Student", b =>
            {
                b.Navigation("Enrollments");
            });
#pragma warning restore 612, 618
        }
    }
}


